// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | HeroSectionSlice
  | ServiceOfferingsSlice
  | BlockContentSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Description field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter Description ( Must )
   * - **API ID Path**: home.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter Title ( Must )
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | ProcessStepsSlice
  | ServiceOfferingsSlice
  | BlockContentSlice;

/**
 * Content for page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Service Post → Service Items*
 */
export interface ServicePostDocumentDataServiceItemsItem {
  /**
   * Service Item field in *Service Post → Service Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., UX/UI Design
   * - **API ID Path**: service_post.service_items[].item
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  item: prismic.KeyTextField;
}

/**
 * Item in *Service Post → Service Offerings → Sub Offerings*
 */
export interface ServicePostDocumentDataServiceOfferingsSubOfferingsItem {
  /**
   * Sub Offering Title field in *Service Post → Service Offerings → Sub Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Books & Magazine
   * - **API ID Path**: service_post.service_offerings[].sub_offerings[].sub_offering_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_offering_title: prismic.KeyTextField;

  /**
   * Sub Offering Description field in *Service Post → Service Offerings → Sub Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of this specific service
   * - **API ID Path**: service_post.service_offerings[].sub_offerings[].sub_offering_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_offering_description: prismic.KeyTextField;
}

/**
 * Item in *Service Post → Service Offerings*
 */
export interface ServicePostDocumentDataServiceOfferingsItem {
  /**
   * Offering Title field in *Service Post → Service Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Editorial
   * - **API ID Path**: service_post.service_offerings[].offering_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  offering_title: prismic.KeyTextField;

  /**
   * Offering Description field in *Service Post → Service Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of this service offering
   * - **API ID Path**: service_post.service_offerings[].offering_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  offering_description: prismic.KeyTextField;

  /**
   * Sub Offerings field in *Service Post → Service Offerings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.service_offerings[].sub_offerings[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sub_offerings: prismic.NestedGroupField<
    Simplify<ServicePostDocumentDataServiceOfferingsSubOfferingsItem>
  >;
}

/**
 * Item in *Service Post → Process Steps → Step Details*
 */
export interface ServicePostDocumentDataProcessStepsStepDetailsItem {
  /**
   * Step Week field in *Service Post → Process Steps → Step Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Week 1, Week 2
   * - **API ID Path**: service_post.process_steps[].step_details[].step_details_week
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_details_week: prismic.KeyTextField;

  /**
   * Step Title field in *Service Post → Process Steps → Step Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Discovery, Research
   * - **API ID Path**: service_post.process_steps[].step_details[].step_details_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_details_title: prismic.KeyTextField;

  /**
   * Step Description field in *Service Post → Process Steps → Step Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of this specific service
   * - **API ID Path**: service_post.process_steps[].step_details[].step_details_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_details_description: prismic.KeyTextField;
}

/**
 * Item in *Service Post → Process Steps*
 */
export interface ServicePostDocumentDataProcessStepsItem {
  /**
   * Step Name field in *Service Post → Process Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Strategy, Creative Concept
   * - **API ID Path**: service_post.process_steps[].step_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_name: prismic.KeyTextField;

  /**
   * Step Description field in *Service Post → Process Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Step details
   * - **API ID Path**: service_post.process_steps[].step_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_description: prismic.RichTextField;

  /**
   * Step Details field in *Service Post → Process Steps*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.process_steps[].step_details[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  step_details: prismic.NestedGroupField<
    Simplify<ServicePostDocumentDataProcessStepsStepDetailsItem>
  >;
}

/**
 * Item in *Service Post → Related Projects*
 */
export interface ServicePostDocumentDataRelatedProjectsItem {
  /**
   * Project field in *Service Post → Related Projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.related_projects[].project
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project: prismic.ContentRelationshipField<"project_post">;
}

type ServicePostDocumentDataSlicesSlice =
  | ServiceHeroSlice
  | ProcessStepsSlice
  | ServiceOfferingsSlice
  | BlockContentSlice;

/**
 * Content for Service Post documents
 */
interface ServicePostDocumentData {
  /**
   * Service Title field in *Service Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter service title
   * - **API ID Path**: service_post.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Service Description field in *Service Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Detailed service description
   * - **API ID Path**: service_post.service_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_description: prismic.RichTextField;

  /**
   * Tagline field in *Service Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Tagline (MUST) e.g, (Define the foundations.  Align your ...)
   * - **API ID Path**: service_post.tagline
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Main Image field in *Service Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Service Items field in *Service Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.service_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service_items: prismic.GroupField<
    Simplify<ServicePostDocumentDataServiceItemsItem>
  >;

  /**
   * Service Offerings field in *Service Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.service_offerings[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service_offerings: prismic.GroupField<
    Simplify<ServicePostDocumentDataServiceOfferingsItem>
  >;

  /**
   * Process Steps field in *Service Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.process_steps[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  process_steps: prismic.GroupField<
    Simplify<ServicePostDocumentDataProcessStepsItem>
  >;

  /**
   * Related Projects field in *Service Post*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.related_projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  related_projects: prismic.GroupField<
    Simplify<ServicePostDocumentDataRelatedProjectsItem>
  >;

  /**
   * Slice Zone field in *Service Post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicePostDocumentDataSlicesSlice> /**
   * Meta Title field in *Service Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO Title
   * - **API ID Path**: service_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: SEO Description
   * - **API ID Path**: service_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service Post document from Prismic
 *
 * - **API ID**: `service_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicePostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServicePostDocumentData>,
    "service_post",
    Lang
  >;

/**
 * Item in *Settings → Navigation Links*
 */
export interface SettingsDocumentDataNavItemsItem {
  /**
   * Link Label field in *Settings → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter link text
   * - **API ID Path**: settings.nav_items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link
   * - **API ID Path**: settings.nav_items[].link_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter site title (e.g. Madamepolare)
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  site_logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.nav_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_items: prismic.GroupField<Simplify<SettingsDocumentDataNavItemsItem>>;

  /**
   * MarqueeText field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Marquee Text ( Must ) e.g (Welcome to our website)
   * - **API ID Path**: settings.marqueetext
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  marqueetext: prismic.KeyTextField;

  /**
   * centeredTitle field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Centered Title ( Must ) e.g. ( Community Agency )
   * - **API ID Path**: settings.centeredtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  centeredtitle: prismic.KeyTextField;

  /**
   * Double Button Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Button Title ( Must ) e.g. ( Let's Talk )
   * - **API ID Path**: settings.double_button_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  double_button_title: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | HomeDocument
  | PageDocument
  | ServicePostDocument
  | SettingsDocument;

/**
 * Item in *BlockContent → Default → Primary → Right Paragraphes*
 */
export interface BlockContentSliceDefaultPrimaryRightParagraphesItem {
  /**
   * Paragraph field in *BlockContent → Default → Primary → Right Paragraphes*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Paragraph
   * - **API ID Path**: block_content.default.primary.right_paragraphes[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *BlockContent → Default → Primary*
 */
export interface BlockContentSliceDefaultPrimary {
  /**
   * Left Paragraph field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Left Paragraph ( Optional )
   * - **API ID Path**: block_content.default.primary.left_paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  left_paragraph: prismic.KeyTextField;

  /**
   * CTA field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Please Enter CTA ( Optional )
   * - **API ID Path**: block_content.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Show CTA field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: block_content.default.primary.show_cta
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_cta: prismic.BooleanField;

  /**
   * Right Paragraphes field in *BlockContent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: block_content.default.primary.right_paragraphes[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  right_paragraphes: prismic.GroupField<
    Simplify<BlockContentSliceDefaultPrimaryRightParagraphesItem>
  >;
}

/**
 * Default variation for BlockContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlockContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlockContent*
 */
type BlockContentSliceVariation = BlockContentSliceDefault;

/**
 * BlockContent Shared Slice
 *
 * - **API ID**: `block_content`
 * - **Description**: BlockContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlockContentSlice = prismic.SharedSlice<
  "block_content",
  BlockContentSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → Team Member Avatars*
 */
export interface HeroSectionSliceDefaultPrimaryAvatarsItem {
  /**
   * Team Member Avatar field in *HeroSection → Default → Primary → Team Member Avatars*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.avatars[].avatar_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  avatar_image: prismic.ImageField<never>;

  /**
   * Avatar Alt Text field in *HeroSection → Default → Primary → Team Member Avatars*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Team member name
   * - **API ID Path**: hero_section.default.primary.avatars[].avatar_alt
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  avatar_alt: prismic.KeyTextField;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * First Row Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: All-in-one
   * - **API ID Path**: hero_section.default.primary.first_row_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  first_row_heading: prismic.KeyTextField;

  /**
   * Main Hero Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Second Row Heading (Before Avatars) field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Creative
   * - **API ID Path**: hero_section.default.primary.second_row_heading_before
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_row_heading_before: prismic.KeyTextField;

  /**
   * Team Member Avatars field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.avatars[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  avatars: prismic.GroupField<
    Simplify<HeroSectionSliceDefaultPrimaryAvatarsItem>
  >;

  /**
   * Second Row Heading (After Avatars) field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: & Design
   * - **API ID Path**: hero_section.default.primary.second_row_heading_after
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  second_row_heading_after: prismic.KeyTextField;

  /**
   * Third Row Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Agency
   * - **API ID Path**: hero_section.default.primary.third_row_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  third_row_heading: prismic.KeyTextField;

  /**
   * Icon Type field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: arrowDown
   * - **API ID Path**: hero_section.default.primary.icon_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon_type: prismic.SelectField<
    | "arrowRight"
    | "arrowLeft"
    | "arrowUp"
    | "arrowDown"
    | "arrowUpRight"
    | "arrowUpLeft"
    | "arrowDownRight"
    | "arrowDownLeft",
    "filled"
  >;

  /**
   * Maximum Visible Avatars field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.max_visible_avatars
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  max_visible_avatars: prismic.NumberField;

  /**
   * Show Plus Sign field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: hero_section.default.primary.show_plus_sign
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_plus_sign: prismic.BooleanField;

  /**
   * Button Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Book a free call
   * - **API ID Path**: hero_section.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;

  /**
   * Button Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Select a link for the button
   * - **API ID Path**: hero_section.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation of Hero Section
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: Hero section with headings, avatar images, and call-to-action button.
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *ProcessSteps → Default → Primary → Process Steps → Step Details*
 */
export interface ProcessStepsSliceDefaultPrimaryStepsStepDetailsItem {
  /**
   * Step Week field in *ProcessSteps → Default → Primary → Process Steps → Step Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Week 1, Week 2
   * - **API ID Path**: process_steps.default.primary.steps[].step_details[].step_details_week
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_details_week: prismic.KeyTextField;

  /**
   * Step Title field in *ProcessSteps → Default → Primary → Process Steps → Step Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Discovery, Research
   * - **API ID Path**: process_steps.default.primary.steps[].step_details[].step_details_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_details_title: prismic.KeyTextField;

  /**
   * Step Description field in *ProcessSteps → Default → Primary → Process Steps → Step Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of this specific service
   * - **API ID Path**: process_steps.default.primary.steps[].step_details[].step_details_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_details_description: prismic.KeyTextField;
}

/**
 * Item in *ProcessSteps → Default → Primary → Process Steps*
 */
export interface ProcessStepsSliceDefaultPrimaryStepsItem {
  /**
   * Step Name field in *ProcessSteps → Default → Primary → Process Steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Strategy, Creative Concept
   * - **API ID Path**: process_steps.default.primary.steps[].step_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  step_name: prismic.KeyTextField;

  /**
   * Step Description field in *ProcessSteps → Default → Primary → Process Steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Step details
   * - **API ID Path**: process_steps.default.primary.steps[].step_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  step_description: prismic.RichTextField;

  /**
   * Step Details field in *ProcessSteps → Default → Primary → Process Steps*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.default.primary.steps[].step_details[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  step_details: prismic.NestedGroupField<
    Simplify<ProcessStepsSliceDefaultPrimaryStepsStepDetailsItem>
  >;
}

/**
 * Primary content in *ProcessSteps → Default → Primary*
 */
export interface ProcessStepsSliceDefaultPrimary {
  /**
   * Process Steps field in *ProcessSteps → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_steps.default.primary.steps[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  steps: prismic.GroupField<Simplify<ProcessStepsSliceDefaultPrimaryStepsItem>>;
}

/**
 * Default variation for ProcessSteps Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessStepsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessStepsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProcessSteps*
 */
type ProcessStepsSliceVariation = ProcessStepsSliceDefault;

/**
 * ProcessSteps Shared Slice
 *
 * - **API ID**: `process_steps`
 * - **Description**: ProcessSteps
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProcessStepsSlice = prismic.SharedSlice<
  "process_steps",
  ProcessStepsSliceVariation
>;

/**
 * Primary content in *ServiceHero → Default → Primary*
 */
export interface ServiceHeroSliceDefaultPrimary {
  /**
   * Service Title field in *ServiceHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Please Enter Service Title ( Must )
   * - **API ID Path**: service_hero.default.primary.service_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_title: prismic.KeyTextField;
}

/**
 * Default variation for ServiceHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceHero*
 */
type ServiceHeroSliceVariation = ServiceHeroSliceDefault;

/**
 * ServiceHero Shared Slice
 *
 * - **API ID**: `service_hero`
 * - **Description**: ServiceHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeroSlice = prismic.SharedSlice<
  "service_hero",
  ServiceHeroSliceVariation
>;

/**
 * Item in *ServiceOfferings → Default → Primary → Service Offerings → Sub Offerings*
 */
export interface ServiceOfferingsSliceDefaultPrimaryServiceOfferingsSubOfferingsItem {
  /**
   * Sub Offering Title field in *ServiceOfferings → Default → Primary → Service Offerings → Sub Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Books & Magazine
   * - **API ID Path**: service_offerings.default.primary.service_offerings[].sub_offerings[].sub_offering_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_offering_title: prismic.KeyTextField;

  /**
   * Sub Offering Description field in *ServiceOfferings → Default → Primary → Service Offerings → Sub Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of this specific service
   * - **API ID Path**: service_offerings.default.primary.service_offerings[].sub_offerings[].sub_offering_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_offering_description: prismic.KeyTextField;
}

/**
 * Item in *ServiceOfferings → Default → Primary → Service Offerings*
 */
export interface ServiceOfferingsSliceDefaultPrimaryServiceOfferingsItem {
  /**
   * Offering Title field in *ServiceOfferings → Default → Primary → Service Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Editorial
   * - **API ID Path**: service_offerings.default.primary.service_offerings[].offering_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  offering_title: prismic.KeyTextField;

  /**
   * Offering Description field in *ServiceOfferings → Default → Primary → Service Offerings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Description of this service offering
   * - **API ID Path**: service_offerings.default.primary.service_offerings[].offering_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  offering_description: prismic.KeyTextField;

  /**
   * Sub Offerings field in *ServiceOfferings → Default → Primary → Service Offerings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_offerings.default.primary.service_offerings[].sub_offerings[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sub_offerings: prismic.NestedGroupField<
    Simplify<ServiceOfferingsSliceDefaultPrimaryServiceOfferingsSubOfferingsItem>
  >;
}

/**
 * Primary content in *ServiceOfferings → Default → Primary*
 */
export interface ServiceOfferingsSliceDefaultPrimary {
  /**
   * Service Offerings field in *ServiceOfferings → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_offerings.default.primary.service_offerings[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  service_offerings: prismic.GroupField<
    Simplify<ServiceOfferingsSliceDefaultPrimaryServiceOfferingsItem>
  >;
}

/**
 * Default variation for ServiceOfferings Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceOfferingsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceOfferingsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceOfferings*
 */
type ServiceOfferingsSliceVariation = ServiceOfferingsSliceDefault;

/**
 * ServiceOfferings Shared Slice
 *
 * - **API ID**: `service_offerings`
 * - **Description**: ServiceOfferings
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceOfferingsSlice = prismic.SharedSlice<
  "service_offerings",
  ServiceOfferingsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServicePostDocument,
      ServicePostDocumentData,
      ServicePostDocumentDataServiceItemsItem,
      ServicePostDocumentDataServiceOfferingsSubOfferingsItem,
      ServicePostDocumentDataServiceOfferingsItem,
      ServicePostDocumentDataProcessStepsStepDetailsItem,
      ServicePostDocumentDataProcessStepsItem,
      ServicePostDocumentDataRelatedProjectsItem,
      ServicePostDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavItemsItem,
      AllDocumentTypes,
      BlockContentSlice,
      BlockContentSliceDefaultPrimaryRightParagraphesItem,
      BlockContentSliceDefaultPrimary,
      BlockContentSliceVariation,
      BlockContentSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryAvatarsItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ProcessStepsSlice,
      ProcessStepsSliceDefaultPrimaryStepsStepDetailsItem,
      ProcessStepsSliceDefaultPrimaryStepsItem,
      ProcessStepsSliceDefaultPrimary,
      ProcessStepsSliceVariation,
      ProcessStepsSliceDefault,
      ServiceHeroSlice,
      ServiceHeroSliceDefaultPrimary,
      ServiceHeroSliceVariation,
      ServiceHeroSliceDefault,
      ServiceOfferingsSlice,
      ServiceOfferingsSliceDefaultPrimaryServiceOfferingsSubOfferingsItem,
      ServiceOfferingsSliceDefaultPrimaryServiceOfferingsItem,
      ServiceOfferingsSliceDefaultPrimary,
      ServiceOfferingsSliceVariation,
      ServiceOfferingsSliceDefault,
    };
  }
}
