// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  block_content: dynamic(() => import("./BlockContent")),
  hero_section: dynamic(() => import("./HeroSection")),
  process_steps: dynamic(() => import("./ProcessSteps")),
  service_hero: dynamic(() => import("./ServiceHero")),
  service_offerings: dynamic(() => import("./ServiceOfferings")),
  services_images_slider: dynamic(() => import("./ServicesImagesSlider")),
};
